// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7LEBLOe1bENqUi8OP9n8sqFcchk82Ao',
    appId: '1:598957117549:web:67c35e29dfee984faeef64',
    messagingSenderId: '598957117549',
    projectId: 'fir-app-18649',
    authDomain: 'fir-app-18649.firebaseapp.com',
    storageBucket: 'fir-app-18649.firebasestorage.app',
    measurementId: 'G-7WM8GHYWX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKnfMjeHt5_yOp34kzAMrYWCsY4BbEyI',
    appId: '1:598957117549:android:62855bb1e36014e0aeef64',
    messagingSenderId: '598957117549',
    projectId: 'fir-app-18649',
    storageBucket: 'fir-app-18649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRSFUS0kHNrhPFI4AbZFReSFapPYMNjuA',
    appId: '1:598957117549:ios:905cfd5ee7bd490aaeef64',
    messagingSenderId: '598957117549',
    projectId: 'fir-app-18649',
    storageBucket: 'fir-app-18649.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRSFUS0kHNrhPFI4AbZFReSFapPYMNjuA',
    appId: '1:598957117549:ios:905cfd5ee7bd490aaeef64',
    messagingSenderId: '598957117549',
    projectId: 'fir-app-18649',
    storageBucket: 'fir-app-18649.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl7LEBLOe1bENqUi8OP9n8sqFcchk82Ao',
    appId: '1:598957117549:web:3ae02922690ca3d7aeef64',
    messagingSenderId: '598957117549',
    projectId: 'fir-app-18649',
    authDomain: 'fir-app-18649.firebaseapp.com',
    storageBucket: 'fir-app-18649.firebasestorage.app',
    measurementId: 'G-NYPX1QMDHQ',
  );
}
